[package]
name = "nxtusb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
examples = []

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
rusb = "0.9"
thiserror = "1"
